// <auto-generated />
using System;
using AzureIoTServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzureIoTServer.Migrations
{
    [DbContext(typeof(IoTDBContext))]
    [Migration("20250119113315_Refactoring")]
    partial class Refactoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AzureIoTServer.Models.ESP32CamLogs", b =>
                {
                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("logMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("dateTime");

                    b.ToTable("esp32Logs");
                });

            modelBuilder.Entity("AzureIoTServer.Models.TempHumidity", b =>
                {
                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("humidity")
                        .HasColumnType("float");

                    b.Property<float>("temperature")
                        .HasColumnType("float");

                    b.HasKey("dateTime");

                    b.ToTable("tempHumidities");
                });
#pragma warning restore 612, 618
        }
    }
}
