// <auto-generated />
using System;
using AzureIoTServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzureIoTServer.Migrations
{
    [DbContext(typeof(IoTDBContext))]
    [Migration("20250115150015_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AzureIoTServer.Models.ESP32CamLogs", b =>
                {
                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("logMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("dateTime");

                    b.ToTable("esp32Logs");
                });

            modelBuilder.Entity("AzureIoTServer.Models.Image", b =>
                {
                    b.Property<long>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ImageId"));

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("imageData")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.HasKey("ImageId");

                    b.ToTable("_images");
                });
#pragma warning restore 612, 618
        }
    }
}
